export enum IdentityRegisterStatusEnum {
  VERIFICATION_IDENTITY=1,
  VERIFICATION_IDENTITY_RESULT_PENDING,
  VERIFICATION_IDENTITY_RETRY,
  VERIFICATION_IDENTITY_RETRY_RESULT_PENDING,
  SUCCESS,
  REJECTED
}
