export enum ParamKeyEnum {
  ARG_ORDER_TRADING_HOUR_FROM = "ARG_ORDER_TRADING_HOUR_FROM",
  ARG_ORDER_TRADING_HOUR_TO = "ARG_ORDER_TRADING_HOUR_TO",
  ARG_FUND_TRADING_HOUR_FROM = "ARG_FUND_TRADING_HOUR_FROM",
  ARG_FUND_TRADING_HOUR_TO = "ARG_FUND_TRADING_HOUR_TO",
  ARG_MEP_TRADING_HOUR_FROM = "ARG_MEP_TRADING_HOUR_FROM",
  ARG_MEP_TRADING_HOUR_TO = "ARG_MEP_TRADING_HOUR_TO",
  ORDER_SURCHARGE_PERCENTAGE = "ORDER_SURCHARGE_PERCENTAGE",
  MEP_SURCHARGE_PERCENTAGE = "MEP_SURCHARGE_PERCENTAGE"
}
